version: "3"

services:
  web:
    image: python_app:version_de_ouf
    environment:
      PORT: 80
      DB_HOST: "db"
    ports:
      - "8080:80"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
