version: "3"

services:
  web:
    image: python_app:version_de_ouf
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1.0'
    environment:
      PORT: 80
      DB_HOST: "db"
    expose:
      - "80" 

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: "db"
    expose:
      - "80" 

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - phpmyadmin
